name: Course materials sauce tests
on: 
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit to test'
        required: true
jobs:
  testing:
    env:
      OOM2_USER: ${{secrets.OOM2_USER}}
      OOM2_PASSWORD: ${{secrets.OOM2_PASSWORD}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}-${{ secrets.GA_CACHE_KEY }}
      - name: Setup sauce connect
        run: |
            curl https://saucelabs.com/downloads/sc-4.6.2-linux.tar.gz -o saucelabs.tar.gz
            tar -xzf saucelabs.tar.gz
            cd sc-*
            bin/sc -u ${{secrets.SAUCE_USERNAME}} -k ${{secrets.SAUCE_KEY}} -i ${{github.run_id}} -f /tmp/sc_ready --no-ssl-bump-domains=127.0.0.1,localhost,dev.muikku.fi --pidfile=/tmp/sc_client.pid &
      - name: Prepare maven settings
        run: python prepare-maven.py
      - name: Build with Maven
        run: mvn clean install --settings ~/.m2/mySettings.xml -Pdummy-mail-plugin,pyramus-plugins,elastic-search-plugin,atests-plugin,timed-notifications-plugin -Dfindbugs.skip=true -Dmaven.javadoc.skip=true -Dsource.skip=true
      - name: Set Muikku host
        run: echo "127.0.0.1 dev.muikku.fi" | sudo tee -a /etc/hosts
      - name: Check sauce connect
        run: |
              while [ ! -f /tmp/sc_ready ]; do
                echo "Waiting for Sauce Connect..."
                sleep 5;
              done;
      - name: Test with chrome
        run: |
            cd muikku-atests
            mvn clean verify --settings ~/.m2/mySettings.xml -Psauce-it -Dmaven.javadoc.skip=true -Dsource.skip=true -Dit.browser="chrome" -Dit.browser.version="latest" -Dit.browser.resolution="1280x1024" -Dit.platform="Windows 10" -Dit.package="course/materials" -Dit.sauce.username=${{secrets.SAUCE_USERNAME}} -Dit.sauce.accessKey=${{secrets.SAUCE_KEY}} -Dit.sauce.tunnelId=${{github.run_id}}
      - name: Read sc_client.pid file
        if: ${{ always() }}
        id: getscpid
        run: echo "::set-output name=scpid::$(cat /tmp/sc_client.pid)"
      - name: Shut Down Sauce Connect Tunnel
        if: ${{ always() }}
        run: |
              kill -2 ${{ steps.getscpid.outputs.scpid }}
              while [ -f /tmp/sc_ready ]; do
                echo "Waiting for Sauce Connect to close..."
                sleep 5;
              done;
